### ISSUE TITLE
bug when loading model

### ISSUE THREAD

**Issue by Philipbear** [JosieHong/3DMolMS#8]
Hi Josie,

I had the following error when testing it.

Load 3 data from ./test/demo_input.csv
Traceback (most recent call last):
  File "/Users/shipei/Documents/projects/playground/3dmolms/trial_3dmolms.py", line 25, in <module>
    pred_spectra_df = molnet_engine.pred_msms(instrument='qtof')
  File "/Users/shipei/miniconda3/lib/python3.8/site-packages/molnetpack/molnet.py", line 163, in pred_msms
    self.load_checkpoint('msms', path_to_checkpoint, instrument)
  File "/Users/shipei/miniconda3/lib/python3.8/site-packages/molnetpack/molnet.py", line 102, in load_checkpoint
    self._download_and_load_checkpoint(checkpoint_path, task_name, instrument)
  File "/Users/shipei/miniconda3/lib/python3.8/site-packages/molnetpack/molnet.py", line 140, in _download_and_load_checkpoint
    self._load_model(checkpoint_path, task_name)
  File "/Users/shipei/miniconda3/lib/python3.8/site-packages/molnetpack/molnet.py", line 150, in _load_model
    model.load_state_dict(torch.load(checkpoint_path, map_location=self.device, weights_only=True)['model_state_dict'])
  File "/Users/shipei/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 788, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 71

Process finished with exit code 1

=====
It looks like you can easily fix it by setting weights_only to False.

Moreover, in the latest PyPI version, **plot_msms** function cannot be directly imported (which I see on your GitHub source code), maybe you want to push a new release to PyPI.
And a typo - in the usage code, it should be 'demo_input.csv' (which you have there).

It is overall a promising tool, and I really look forward to using it. 

Thanks,
Shipei

**Comment by JosieHong** [comment]
Thank you for evaluating this model! Could you provide more details about how you ran it? I ran the example commands, correcting the typo in the input file name to `./test/demo_input.csv`, on my device but could not reproduce the error. 

I don’t think setting `weights_only` to False will fix the bug because the weights are indeed for the weights only. Perhaps we could check the version of PyTorch to see if the issue is caused by version differences. Additionally, `plot_msms` can be imported using `from molnetpack import MolNet, plot_msms`. Could you please check this again? 

The following is the environment I used. Checking the versions of **PyTorch** and **molnetpack** might help. Please let me know if there are any updates. I am more than happy to fix the bug!  
```
# packages in environment at /home/j0siee/anaconda3/envs/tmp_debug:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   2.1.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blas                      1.0                         mkl
brotli-python             1.0.9           py312h6a678d5_8
bzip2                     1.0.8                h5eee18b_6
ca-certificates           2024.11.26           h06a4308_0
certifi                   2024.12.14      py312h06a4308_0
charset-normalizer        3.3.2              pyhd3eb1b0_0
contourpy                 1.3.1                    pypi_0    pypi
cpuonly                   2.0                           0    pytorch
cycler                    0.12.1                   pypi_0    pypi
expat                     2.6.4                h6a678d5_0
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1          py312h06a4308_0
fonttools                 4.55.3                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
gdown                     5.2.0                    pypi_0    pypi
giflib                    5.2.2                h5eee18b_0
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
grpcio                    1.68.1                   pypi_0    pypi
idna                      3.7             py312h06a4308_0
importlib-metadata        8.5.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306
jinja2                    3.1.4           py312h06a4308_1
jpeg                      9e                   h5eee18b_3
kiwisolver                1.4.7                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lcms2                     2.16                 hb9589c4_0
ld_impl_linux-64          2.40                 h12ee557_0
lerc                      4.0.0                h6a678d5_0
libdeflate                1.22                 h5eee18b_0
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libiconv                  1.16                 h5eee18b_3
libidn2                   2.3.4                h5eee18b_0
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libpng                    1.6.39               h5eee18b_0
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.1                hffd6297_1
libunistring              0.9.10               h27cfd23_0
libuuid                   1.41.5               h5eee18b_0
libwebp                   1.3.2                h11a3e52_0
libwebp-base              1.3.2                h5eee18b_1
llvm-openmp               14.0.6               h9e868ea_0
lxml                      5.3.0                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1
markdown                  3.7                      pypi_0    pypi
markupsafe                2.1.3           py312h5eee18b_0
matplotlib                3.10.0                   pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344
mkl-service               2.4.0           py312h5eee18b_1
mkl_fft                   1.3.11          py312h5eee18b_0
mkl_random                1.2.8           py312h526ad5a_0
molmass                   2024.10.25               pypi_0    pypi
molnetpack                1.1.10                   pypi_0    pypi
mpmath                    1.3.0           py312h06a4308_0
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  3.2.1           py312h06a4308_0
numpy                     2.1.3           py312hc5e2394_0
numpy-base                2.1.3           py312h0da6c21_0
openh264                  2.1.1                h4ff587b_0
openjpeg                  2.5.2                he7f1fd0_0
openssl                   3.0.15               h5eee18b_0
packaging                 24.2                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
pillow                    11.0.0          py312hcea889d_1
pip                       24.2            py312h06a4308_0
protobuf                  5.29.2                   pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pysocks                   1.7.1           py312h06a4308_0
pyteomics                 4.7.5                    pypi_0    pypi
python                    3.12.8               h5148396_0
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch                   2.5.1              py3.12_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2           py312h5eee18b_0
rdkit                     2024.3.6                 pypi_0    pypi
readline                  8.2                  h5eee18b_0
requests                  2.32.3          py312h06a4308_1
setuptools                72.1.0          py312h06a4308_0
six                       1.17.0                   pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0
sympy                     1.13.3          py312h06a4308_0
tbb                       2021.8.0             hdb19cb5_0
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tk                        8.6.14               h39e8969_0
torchaudio                2.5.1                 py312_cpu    pytorch
torchvision               0.20.1                py312_cpu    pytorch
tqdm                      4.67.1                   pypi_0    pypi
typing_extensions         4.11.0          py312h06a4308_0
tzdata                    2024.2                   pypi_0    pypi
urllib3                   2.2.3           py312h06a4308_0
werkzeug                  3.1.3                    pypi_0    pypi
wheel                     0.44.0          py312h06a4308_0
xz                        5.4.6                h5eee18b_1
yaml                      0.2.5                h7b6447c_0
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1
zstd                      1.5.6                hc292b87_0
```

Best,
Josie

**Comment by Philipbear** [comment]
Thanks for the quick response!

Here is a test case on [Google Colab](https://colab.research.google.com/drive/1eaZUWzx-siH1e-VT-qQ3cHfME7CZfA42?usp=sharing).

The model is now loaded correctly.

For the import issue, I see you have updates recently that have not been pushed onto PyPI release - that's why.

Thanks,
Shipei
